-- operativna_baza_podataka

CREATE TABLE punjenja (
    id INT AUTO_INCREMENT PRIMARY KEY,
    poslednje_punjenje DATETIME
);


CREATE TABLE `Vreme` (
  IdVre INT AUTO_INCREMENT,
  VremeDatum DATETIME UNIQUE,
  PRIMARY KEY (IdVre)
);

-- Kreiranje tabele MESTO
CREATE TABLE MESTO (
    IdMes INT NOT NULL,
    Mesto VARCHAR(255),
    PRIMARY KEY(IdMes)
);

-- Kreiranje tabele KORISNIK
CREATE TABLE KORISNIK (
    IdKor INT NOT NULL,
    Ime VARCHAR(255),
    Prezime VARCHAR(255),
    Mobilni VARCHAR(20),
    Email VARCHAR(255),
    Godiste INT,
    Pol VARCHAR(10),
    IdM INT,
    FOREIGN KEY (IdM) REFERENCES MESTO(IdMes),
    PRIMARY KEY(IdKor)
);

-- Kreiranje tabele KATEGORIJA
CREATE TABLE KATEGORIJA (
    IdKat INT NOT NULL,
    Naziv VARCHAR(255),
    PRIMARY KEY(IdKat)
);

-- Kreiranje tabele ARTIKAL
CREATE TABLE ARTIKAL (
    IdArt INT NOT NULL,
    Naziv VARCHAR(255),
    Opis TEXT,
    Cena DECIMAL(10, 2),
    Popust DECIMAL(10, 2),
    Kolicina INT,
    IdKor INT,
    IdKat INT,
    FOREIGN KEY (IdKor) REFERENCES KORISNIK(IdKor),
    FOREIGN KEY (IdKat) REFERENCES KATEGORIJA(IdKat),
    PRIMARY KEY(IdArt)
);

-- Kreiranje tabele NARUDZBINA
CREATE TABLE NARUDZBINA (
    IdNar INT NOT NULL,
    IdKor INT,
    Datum DATE,
    Vreme TIME,
    Iznos DECIMAL(10, 2),
    FOREIGN KEY (IdKor) REFERENCES KORISNIK(IdKor),
    PRIMARY KEY(IdNar)
);

-- Kreiranje tabele STAVKA
CREATE TABLE STAVKA (
    IdNar INT,
    IdArt INT,
    Iznos DECIMAL(10, 2),
    Kolicina INT,
    FOREIGN KEY (IdNar) REFERENCES NARUDZBINA(IdNar),
    FOREIGN KEY (IdArt) REFERENCES ARTIKAL(IdArt),
    PRIMARY KEY (IdNar, IdArt)
);

-- Kreiranje tabele KORPA
CREATE TABLE KORPA (
    IdKor INT,
    IdArt INT,
    Kolicina INT,
    FOREIGN KEY (IdKor) REFERENCES KORISNIK(IdKor),
    FOREIGN KEY (IdArt) REFERENCES ARTIKAL(IdArt),
    PRIMARY KEY (IdKor, IdArt)
);

-- Kreiranje tabele RECENZIJA
CREATE TABLE RECENZIJA (
    IdKor INT,
    IdArt INT,
    Ocena INT,
    Opis TEXT,
    Datum DATE,
    Vreme TIME,
    FOREIGN KEY (IdKor) REFERENCES KORISNIK(IdKor),
    FOREIGN KEY (IdArt) REFERENCES ARTIKAL(IdArt)
);

ALTER TABLE MESTO ADD COLUMN VremePoslednjeIzmene DATETIME;
ALTER TABLE KORISNIK ADD COLUMN VremePoslednjeIzmene DATETIME;
ALTER TABLE KATEGORIJA ADD COLUMN VremePoslednjeIzmene DATETIME;
ALTER TABLE ARTIKAL ADD COLUMN VremePoslednjeIzmene DATETIME;
-- ALTER TABLE NARUDZBINA ADD COLUMN VremePoslednjegUnosa DATETIME;
ALTER TABLE STAVKA ADD COLUMN VremeUnosa DATETIME;
ALTER TABLE KORPA ADD COLUMN VremePoslednjegUnosa DATETIME;
-- ALTER TABLE RECENZIJA ADD COLUMN VremePoslednjegUnosa DATETIME;

-- Trigger Mesto

DELIMITER $$
CREATE TRIGGER trg_MESTO_IZMENA
BEFORE UPDATE ON MESTO
FOR EACH ROW
BEGIN
    SET NEW.VremePoslednjeIzmene = CURRENT_TIMESTAMP();
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER trg_MESTO_UNOS
BEFORE INSERT ON MESTO
FOR EACH ROW
BEGIN
    SET NEW.VremePoslednjeIzmene = CURRENT_TIMESTAMP();
END$$
DELIMITER ;


-- Trigger Korisnik

DELIMITER $$
CREATE TRIGGER trg_KORISNIK_IZMENA
BEFORE UPDATE ON KORISNIK
FOR EACH ROW
BEGIN
    SET NEW.VremePoslednjeIzmene = CURRENT_TIMESTAMP();
END$$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER trg_KORISNIK_UNOS
BEFORE INSERT ON KORISNIK
FOR EACH ROW
BEGIN
    SET NEW.VremePoslednjeIzmene = CURRENT_TIMESTAMP();
END$$
DELIMITER ;

-- Triger Kategorija

DELIMITER $$
CREATE TRIGGER trg_KATEGORIJA_IZMENA
BEFORE UPDATE ON KATEGORIJA
FOR EACH ROW
BEGIN
    SET NEW.VremePoslednjeIzmene = CURRENT_TIMESTAMP();
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER trg_KATEGORIJA_UNOS
BEFORE INSERT ON KATEGORIJA
FOR EACH ROW
BEGIN
    SET NEW.VremePoslednjeIzmene = CURRENT_TIMESTAMP();
END$$
DELIMITER ;


-- Trigger ARTIKAL

DELIMITER $$
CREATE TRIGGER trg_ARTIKAL_IZMENA
BEFORE UPDATE ON ARTIKAL
FOR EACH ROW
BEGIN
    SET NEW.VremePoslednjeIzmene = CURRENT_TIMESTAMP();
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER trg_ARTIKAL_UNOS
BEFORE INSERT ON ARTIKAL
FOR EACH ROW
BEGIN
    SET NEW.VremePoslednjeIzmene = CURRENT_TIMESTAMP();
END$$
DELIMITER ;

-- Trigger NARUDZBINA

DELIMITER $$
CREATE TRIGGER trg_NARUDZBINA_UNOS
BEFORE INSERT ON NARUDZBINA
FOR EACH ROW
BEGIN
    INSERT IGNORE INTO vreme (VremeDatum)
    VALUES (CAST(CONCAT(NEW.Datum, ' ', NEW.Vreme) AS DATETIME));
END$$
DELIMITER ;

-- Trigger STAVKA

DELIMITER $$
CREATE TRIGGER trg_STAVKA_UNOS
BEFORE INSERT ON STAVKA
FOR EACH ROW
BEGIN
    SET NEW.VremeUnosa = CURRENT_TIMESTAMP();
END$$
DELIMITER ;


-- Trigger KORPA

DELIMITER $$
CREATE TRIGGER trg_KORPA_UNOS
BEFORE INSERT ON KORPA
FOR EACH ROW
BEGIN
    SET NEW.VremePoslednjegUnosa = CURRENT_TIMESTAMP();
END$$
DELIMITER ;


-- Trigger RECENZIJA

DELIMITER $$
CREATE TRIGGER trg_RECENZIJA_UNOS
BEFORE INSERT ON RECENZIJA
FOR EACH ROW
BEGIN
    INSERT IGNORE INTO vreme (VremeDatum)
    VALUES (CAST(CONCAT(NEW.Datum, ' ', NEW.Vreme) AS DATETIME));
END$$
DELIMITER ;


-- DROP Ako zatreba
-- DROP TRIGGER IF EXISTS trg_MESTO_IZMENA;
